version: "3.7"

services:
  mongodb:
    image: mongo:4.4.2
    container_name: artyom-ganev-node
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - ${MONGO_PORT:-27017}:27017
    networks:
      - backend

networks:
  backend:
